module.exports = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  SIGNUP: 'SIGNUP',
  ADD_CULTURE: 'ADD_CULTURE',
  GET_CULTURE_START: 'GET_CULTURE_START',
  GET_CULTURE_ERROR: 'GET_CULTURE_ERROR',
  REMOVE_CULTURE: 'REMOVE_CULTURE'
}
